
#bot token
#7370013177:AAEW7jrJGtBjCvovLSDnwLbxi90cV0aDT54
#chat id
#-1002171850152


groups:
  # Alerts group for VM single assumes that Grafana dashboard
  # https://grafana.com/grafana/dashboards/10229 is installed.
  # Pls update the `dashboard` annotation according to your setup.
  - name: vmsingle
    interval: 30s
    concurrency: 2
    rules:
      - alert: DiskRunsOutOfSpaceIn3Days
        expr: |
          vm_free_disk_space_bytes / ignoring(path)
          (
            rate(vm_rows_added_to_storage_total[1d])
            * scalar(
              sum(vm_data_size_bytes{type!~"indexdb.*"}) /
              sum(vm_rows{type!~"indexdb.*"})
             )
          ) < 3 * 24 * 3600 > 0
        for: 35m
        labels:
          severity: critical
        annotations:
          dashboard: "http://localhost:3000/d/wNf0q_kZk?viewPanel=73&var-host={{ $labels.host }}"
          summary: "host {{ $labels.host }} will run out of disk space soon"
          description: "Taking into account current ingestion rate, free disk space will be enough only
            for {{ $value | humanizeDuration }} on host {{ $labels.host }}.\n
            Consider to limit the ingestion rate, decrease retention or scale the disk space if possible."

      - alert: DiskRunsOutOfSpace
        expr: |
          sum(vm_data_size_bytes) by(job, host) /
          (
           sum(vm_free_disk_space_bytes) by(job, host) +
           sum(vm_data_size_bytes) by(job, host)
          ) > 0.8
        for: 35m
        labels:
          severity: critical
        annotations:
          dashboard: "http://localhost:3000/d/wNf0q_kZk?viewPanel=53&var-host={{ $labels.host }}"
          summary: "host {{ $labels.host }} (job={{ $labels.job }}) will run out of disk space soon"
          description: "Disk utilisation on host {{ $labels.host }} is more than 80%.\n
            Having less than 20% of free disk space could cripple merges processes and overall performance.
            Consider to limit the ingestion rate, decrease retention or scale the disk space if possible."

      - alert: RequestErrorsToAPI
        expr: increase(vm_http_request_errors_total[5m]) > 0
        for: 15m
        labels:
          severity: warning
        annotations:
          dashboard: "http://localhost:3000/d/wNf0q_kZk?viewPanel=35&var-host={{ $labels.host }}"
          summary: "Too many errors served for path {{ $labels.path }} (host {{ $labels.host }})"
          description: "Requests to path {{ $labels.path }} are receiving errors.
            Please verify if clients are sending correct requests."

      - alert: RowsRejectedOnIngestion
        expr: rate(vm_rows_ignored_total[5m]) > 0
        for: 15m
        labels:
          severity: warning
        annotations:
          dashboard: "http://localhost:3000/d/wNf0q_kZk?viewPanel=58&var-host={{ $labels.host }}"
          summary: "Some rows are rejected on \"{{ $labels.host }}\" on ingestion attempt"
          description: "VM is rejecting to ingest rows on \"{{ $labels.host }}\" due to the
            following reason: \"{{ $labels.reason }}\""

      - alert: TooHighChurnRate
        expr: |
          (
             sum(rate(vm_new_timeseries_created_total[5m])) by(host)
             /
             sum(rate(vm_rows_inserted_total[5m])) by (host)
           ) > 0.1
        for: 15m
        labels:
          severity: warning
        annotations:
          dashboard: "http://localhost:3000/d/wNf0q_kZk?viewPanel=66&var-host={{ $labels.host }}"
          summary: "Churn rate is more than 10% on \"{{ $labels.host }}\" for the last 15m"
          description: "VM constantly creates new time series on \"{{ $labels.host }}\".\n
            This effect is known as Churn Rate.\n
            High Churn Rate tightly connected with database performance and may
            result in unexpected OOM's or slow queries."

      - alert: TooHighChurnRate24h
        expr: |
          sum(increase(vm_new_timeseries_created_total[24h])) by(host)
          >
          (sum(vm_cache_entries{type="storage/hour_metric_ids"}) by(host) * 3)
        for: 15m
        labels:
          severity: warning
        annotations:
          dashboard: "http://localhost:3000/d/wNf0q_kZk?viewPanel=66&var-host={{ $labels.host }}"
          summary: "Too high number of new series on \"{{ $labels.host }}\" created over last 24h"
          description: "The number of created new time series over last 24h is 3x times higher than
            current number of active series on \"{{ $labels.host }}\".\n
            This effect is known as Churn Rate.\n
            High Churn Rate tightly connected with database performance and may
            result in unexpected OOM's or slow queries."

      - alert: TooHighSlowInsertsRate
        expr: |
          (
             sum(rate(vm_slow_row_inserts_total[5m])) by(host)
             /
             sum(rate(vm_rows_inserted_total[5m])) by (host)
           ) > 0.05
        for: 15m
        labels:
          severity: warning
        annotations:
          dashboard: "http://localhost:3000/d/wNf0q_kZk?viewPanel=68&var-host={{ $labels.host }}"
          summary: "Percentage of slow inserts is more than 5% on \"{{ $labels.host }}\" for the last 15m"
          description: "High rate of slow inserts on \"{{ $labels.host }}\" may be a sign of resource exhaustion
            for the current load. It is likely more RAM is needed for optimal handling of the current number of active time series.
            See also https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3976#issuecomment-1476883183"

      - alert: LabelsLimitExceededOnIngestion
        expr: increase(vm_metrics_with_dropped_labels_total[5m]) > 0
        for: 15m
        labels:
          severity: warning
        annotations:
          dashboard: "http://localhost:3000/d/wNf0q_kZk?viewPanel=74&var-host={{ $labels.host }}"
          summary: "Metrics ingested in ({{ $labels.host }}) are exceeding labels limit"
          description: "VictoriaMetrics limits the number of labels per each metric with `-maxLabelsPerTimeseries` command-line flag.\n
           This prevents from ingesting metrics with too many labels. Please verify that `-maxLabelsPerTimeseries` is configured
           correctly or that clients which send these metrics aren't misbehaving."

      - alert: HostHighCpuLoad
        expr: 100 - (avg by(host) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 90
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Host high CPU load (host {{ $labels.host }})
          description: "CPU load is > 90% Current usage: {{ $value }}%"

      - alert: HostHighRAMLoad
        expr: (1 - (avg by(host) (node_memory_MemAvailable_bytes) / avg by(host) (node_memory_MemTotal_bytes))) * 100 > 80
        for: 10m  
        labels:
          severity: warning
        annotations:
          summary: "Host high RAM load (host {{ $labels.host }})"
          description: "RAM usage is above 80%. Current usage: {{ $value }}%"

      - alert: HostHighROMLoad
        expr: 100 - ((avg by(host) (node_filesystem_avail_bytes{mountpoint="/",fstype!="rootfs"}) * 100) / avg by(host) (node_filesystem_size_bytes{mountpoint="/",fstype!="rootfs"})) > 80
        for: 10m  
        labels:
          severity: warning
        annotations:
          summary: "Host high ROM load (host {{ $labels.host }})"
          description: "ROM usage is above 80%. Current usage: {{ $value }}%"

      - alert: HostRestart
        expr: avg by(host) (node_time_seconds - node_boot_time_seconds) < 300
        for: 10m  
        labels:
          severity: critical
        annotations:
          summary: "Host restarted (host {{ $labels.host }})"
          description: "Host uptime less then 3m. Current uptime: {{ $value }}%"


      