cluster.name: "my-cluster"
node.name: "primary-node"
discovery.type: "single-node"
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

xpack.ccr.enabled: true

#   curl -X PUT "localhost:9200/leader-index" -H 'Content-Type: application/json' -d'
# {
#   "settings": {
#     "number_of_shards": 1,
#     "number_of_replicas": 0
#   }
# }
# '