{
 "title": "Nginx metrics",
 "description": "Browse, analyze logs in Elasticsearchstatus_codes, pie-chart, top 10 clientip, line-chart,word-map and etc...",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "domain",
    "label": "Domain Name",
    "query": "{\"find\":\"terms\",\"field\":\"domain.keyword\"}"
   },
   {
    "name": "status",
    "label": "Status Code",
    "query": "{\"find\":\"terms\",\"field\":\"status\"}"
   },
   { "name": "responsetime", "label": "Response Time", "query": "1,2,3,4,5,10" },
   {
    "name": "inter",
    "label": "Interval",
    "query": "1s,5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "RPM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MIN RPM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AVG RPM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MAX RPM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MAX RPM",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "alias": "Request per minutes",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MIN RPM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AVG RPM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MAX RPM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MIN RPM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AVG RPM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MAX RPM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "RTPM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "MIN RTPM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "responsetime", "id": "3", "type": "min" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AVG RTPM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "responsetime", "id": "3", "type": "avg" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MAX RTPM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "responsetime", "id": "3", "type": "max" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MAX RTPM",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 14 },
   "targets": [
    {
     "alias": "Response Time",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "responsetime", "id": "3", "type": "max" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    },
    {
     "alias": "percentile 25",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "responsetime", "id": "3", "settings": { "percents": [ "25" ] }, "type": "percentiles" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    },
    {
     "alias": "percentile 50",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "responsetime", "id": "3", "settings": { "percents": [ "50" ] }, "type": "percentiles" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    },
    {
     "alias": "percentile 75",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "responsetime", "id": "3", "settings": { "percents": [ "75" ] }, "type": "percentiles" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    },
    {
     "alias": "percentile 95",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "responsetime", "id": "3", "settings": { "percents": [ "95" ] }, "type": "percentiles" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    },
    {
     "alias": "percentile 99",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "responsetime", "id": "3", "settings": { "percents": [ "99" ] }, "type": "percentiles" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MIN RTPM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "responsetime", "id": "3", "type": "min" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AVG RTPM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "responsetime", "id": "3", "type": "avg" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MAX RTPM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "responsetime", "id": "3", "type": "max" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MIN RTPM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "responsetime", "id": "3", "type": "min" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AVG RTPM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "responsetime", "id": "3", "type": "avg" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MAX RTPM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "responsetime", "id": "3", "type": "max" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inter", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ip.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "domain:$domain and user_agent!='MSIE' and user_agent!='Zabbix'",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain Average Response Time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "responsetime",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "domain:$domain",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain Request method percentage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 27 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "request_method.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain and user_agent!='MSIE' and user_agent!='Zabbix'",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain HTTP Status Code",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 27 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "status",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain and user_agent!='MSIE' and user_agent!='Zabbix'",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain IP TOP 10",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "client.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain and user_agent!='MSIE' and user_agent!='Zabbix'",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain host TOP 10",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "hostname.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain request top 10 w/o static files",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "extracted_request.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain AND NOT request:\"/static/*\" AND NOT request:\"/media/*\" AND NOT request:\"/web-client/*\" AND NOT request:\"/redash/*\" AND NOT request:\"/lk/*\" AND NOT request:\"/favicon.ico\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain request top 10",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 49 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "extracted_request.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain and user_agent!='MSIE' and user_agent!='Zabbix'",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain request top 10",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "extracted_request.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "field": "responsetime",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" },
      { "field": "responsetime", "id": "5", "type": "max" }
     ],
     "query": "domain:$domain ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain referer top 10",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "referer.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain and user_agent!='MSIE' and user_agent!='Zabbix'",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain user_agent top 10",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 79 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http_user_agent.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain and user_agent!='MSIE' and user_agent!='Zabbix'",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Historical Trends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$domain Request count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inter", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain and user_agent!='MSIE' and user_agent!='Zabbix'",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain HTTP Status Code",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "none", "label": "状态码数量" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "status",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inter", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain and user_agent!='MSIE' and user_agent!='Zabbix'",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain Slow response time >$responsetime s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inter", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain AND responsetime:[$responsetime TO 100] and user_agent!='MSIE' and user_agent!='Zabbix'",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}