apiVersion: 1

datasources:
    - name: VictoriaMetrics
      type: prometheus
      access: proxy
      url: http://vmauth:8427/
      isDefault: true
      basicAuth: true
      basicAuthUser: alerting
      basicAuthPassword: password
      editable: true
    - name: elasticsearch
      type: Elasticsearch
      access: proxy
      url: http://elasticsearch:9200/
      isDefault: false
      basicAuth: true
      basicAuthUser: elastic
      basicAuthPassword: password
      editable: true 