services:
  node-exporter:
    image: prom/node-exporter:v1.7.0
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 127.0.0.1:9100:9100
    networks:
      - exporters   
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "7"

  pusher:
    container_name: pusher
    image: aay98/pusher
    build:
      context: pusher
    networks:
      - exporters
    environment:
      - HOST=${HOST}
      - LOGIN=${LOGIN}
      - PASS=${PASS}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "7"

  filebeat:
    user: root
    container_name: filebeat
    image: elastic/filebeat:7.17.18
    volumes:
      - /var/run/docker.sock:/host_docker/docker.sock
      - /var/lib/docker:/host_docker/var/lib/docker
      - /var/log/nginx:/usr/share/filebeat/mylog
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    command: ["--strict.perms=false"]
    environment:
      - LOGSTASH_HOSTS=$LOGSTASH_HOSTS
      - PROXY_URL=$PROXY_URL
    ulimits:
      memlock:
        soft: -1
        hard: -1
    stdin_open: true
    tty: true
    deploy:
      mode: global
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "7"
    networks:
      - exporters


networks:
  exporters:
    name: exporters-networks
