filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/mylog/*.log

output.logstash:
  hosts: ["${LOGSTASH_HOSTS}"]
  proxy_url: "${PROXY_URL}"

processors:
  - add_docker_metadata:
      host: "unix:///host_docker/docker.sock"

logging:
  level: info
  to_files: true
  files:
    path: /var/log/filebeat
    name: filebeat
    keepfiles: 7
    permissions: 0644